
# -*- coding: utf-8 -*-
"""tbd.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lNqu3ViBwWsvP8Nx07YdJAUFd44pnv5O
"""

from importlib import util as iutil


def tampil(sql):
    lib1 = iutil.spec_from_file_location(
        "connectDB", "C:/xampp/htdocs/collaborations/speedrun-tbd/functions/connectDB.py")
    lib2 = iutil.spec_from_file_location(
        "insertMany", "C:/xampp/htdocs/collaborations/speedrun-tbd/functions/display.py")
    connectDB = iutil.module_from_spec(lib1)
    displayData = iutil.module_from_spec(lib2)

    lib1.loader.exec_module(connectDB)
    lib2.loader.exec_module(displayData)

    # test connection successful
    connect = connectDB.connection(
        "localhost", "root", "root", "db_tokomainan")

    results = displayData.read_query(connect, sql)
    return results


def tambah(sql, val):
    lib1 = iutil.spec_from_file_location(
        "connectDB", "C:/xampp/htdocs/collaborations/speedrun-tbd/functions/connectDB.py")
    lib2 = iutil.spec_from_file_location(
        "insertMany", "C:/xampp/htdocs/collaborations/speedrun-tbd/functions/insertMany.py")

    connectDB = iutil.module_from_spec(lib1)
    insertMany = iutil.module_from_spec(lib2)

    lib1.loader.exec_module(connectDB)
    lib2.loader.exec_module(insertMany)

    # test connection successful
    connect = connectDB.connection(
        "localhost", "root", "root", "db_tokomainan")

    insertMany.insertMany(connect, sql, val)


def tampilMainan():
    sqlProduk = '''
      SELECT *
      FROM tbl_produk;
      '''
    result = tampil(sqlProduk)
    for res in result:
        print(res)

    return result


def tampilPembeli():
    sqlPembeli = '''
      SELECT *
      FROM tbl_pembeli;
      '''
    result = tampil(sqlPembeli)
    for res in result:
        print(res)

    return result


def tambahMainan():
    namaProduk = input('Nama Mainan: ')
    harga = int(input('Harga Mainan: '))

    sqlProduk = '''
      INSERT INTO tbl_produk ( namaProduk, harga) 
      VALUES ( %s, %s)
      '''

    valProduk = [
        (namaProduk, harga)
    ]

    tambah(sqlProduk, valProduk)


def ubahMainan():
    namaProduk = input('Nama Mainan yang ingin diubah: ')
    harga = int(input('Harga baru Mainan: '))
    # update di tbl_produk


def hapusMainan():
    namaProduk = input('Nama Mainan yang ingin dihapus: ')
    # delete dari tbl_produk


def tambahPelanggan():
    namaPembeli = input('Nama Pembeli: ')
    alamat = input('Alamat Pembeli: ')
    hp = input('No HP Pembeli: ')

    sqlPembeli = '''
      INSERT INTO tbl_pembeli ( namaPembeli, alamat, hp) 
      VALUES ( %s, %s, %s)
      '''

    valPembeli = [
        ('Naufal', 'Tlogosari Raya', '0812345678'),
        ('Jimmy', 'Pedurungan Timur', '0814327682')
    ]

    tambah(sqlPembeli, valPembeli)


def catatPemesanan():
    tampilPembeli()
    idPembeli = int(input('ID Pelanggan yang beli: '))

    tampilMainan()
    idProduk = int(input('ID Mainan yang dibeli: '))

    harga = 0  # ambil harga produk yang dibeli
    jumlah = int(input('Jumlah beli: '))
    total = jumlah * harga
    from datetime import date
    tanggal = date.today()

    idProduk = 0  # ambil id produk pakai read tbl_produk
    idPembeli = 0  # ambil id pembeli pakai read tbl_pembeli

    # insert ke tbl_pemesanan


def main():
    pilih = 0

    while pilih != 7:
        print('-= TOKO MAINAN UHUY =-')
        print('1. Lihat Etalase Mainan')
        print('2. Tambah Mainan')
        print('3. Ubah Mainan')
        print('4. Hapus Mainan')
        print('5. Tambah Pelanggan')
        print('6. Catat Pemesanan Mainan')
        print('7. Keluar')

        pilih = int(input('Pilih Operasi: '))

        if pilih == 1:
            tampilMainan()
        if pilih == 2:
            tambahMainan()
        if pilih == 3:
            ubahMainan()
        if pilih == 4:
            hapusMainan()
        if pilih == 5:
            tambahPelanggan()
        if pilih == 6:
            catatPemesanan()


if __name__ == '__main__':
    main()
